### ISSUE TITLE
It works but reel is private

### ISSUE THREAD

**Issue by pydemo** [XavierZambrano/facebook-reels-api#2]
%subj%
Any idea why?
my perms:

publish_video
pages_show_list
pages_read_engagement
pages_manage_posts

**Comment by XavierZambrano** [comment]
Your app is still in development mode

[https://stackoverflow.com/q/76984265/19530478](https://stackoverflow.com/q/76984265/19530478)

**Comment by pydemo** [comment]
thank you . i needed more prerms:

publish_video
pages_show_list
business_management
pages_read_engagement
pages_manage_posts
public_profile

it works now
