### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by dafidxcode** [XavierZambrano/facebook-reels-api#3]
Result success but not showing reels on page

**Comment by XavierZambrano** [comment]
Check your permissions and ensure that your app is not in development mode. (Only you will be able to see the reels when in development mode.)

https://github.com/XavierZambrano/facebook-reels-api/issues/2

**Comment by dafidxcode** [comment]
Bro, can u make upload reel to pages with cookie?

**Comment by XavierZambrano** [comment]
It’s not part of my plans, but the API exists, and you can easily access it

**Comment by dafidxcode** [comment]
Tokens cannot last long, only a matter of hours, which is different from when we use cookies
